const projects=[
{name:'Relay',language:'Go',description:'Durable event relay for PostgreSQL. Replays missed webhooks, batches delivery, and exposes lag without asking operators to babysit another queue.',tags:['Go','PostgreSQL','Webhooks','SSE']},
{name:'Atlas',language:'Go',description:'A tiny service catalog that maps owners, runbooks, dependencies, and deploy history into one searchable graph for incident response.',tags:['Go','Graph','OpenAPI']},
{name:'Pulse',language:'Rust',description:'Low-overhead synthetic monitor with regional probes, percentile-aware alerts, and a deliberately boring single-binary deployment.',tags:['Rust','HTTP','Telemetry']},
{name:'Quarry',language:'Go',description:'Postgres-backed job runner with leases, retries, dead-letter inspection, and graceful handoff during rolling deploys.',tags:['Go','PostgreSQL','Queues']},
{name:'Lattice',language:'TypeScript',description:'Schema-first feature configuration. Validates changes before rollout and ships a compact, cache-friendly SDK for edge runtimes.',tags:['TypeScript','Edge','Redis']},
{name:'Northstar',language:'Go',description:'A deployment diff tool that explains what changed across environments before production becomes the place you discover it.',tags:['Go','Kubernetes','Diff']},
{name:'Kiln',language:'Go',description:'Concurrent asset pipeline that fingerprints, compresses, and publishes build artifacts with deterministic manifests.',tags:['Go','S3','Builds']},
{name:'Beacon',language:'Python',description:'Incident timeline generator that turns audit logs, deploys, and alerts into a shared chronology while the details are still fresh.',tags:['Python','Events','Ops']},
{name:'Tandem',language:'Go',description:'A compact reverse proxy for local service meshes with request mirroring, circuit breaking, and zero-config mTLS.',tags:['Go','TCP/IP','mTLS']},
{name:'Ledger',language:'Ruby',description:'Append-only accounting core with idempotent writes, explicit reversals, and property-tested balance invariants.',tags:['Ruby','PostgreSQL','Finance']},
{name:'Nomad',language:'Go',description:'A resilient command runner for unreliable networks, built around resumable streams and cryptographically signed jobs.',tags:['Go','gRPC','CLI']},
{name:'Basalt',language:'C',description:'An educational key-value store built from the page cache up: WAL, B+ tree, snapshots, and crash-recovery tests included.',tags:['C','Storage','WAL']},
{name:'Static',language:'Go',description:'A zero-dependency status page server with signed updates, incident subscriptions, and a 9 MB production image.',tags:['Go','SQLite','Docker']}
];
const posts={notes:[['Reliable background jobs and retries','Backend'],['PostgreSQL durability and write-ahead logging','Database'],['Idempotent APIs and failure recovery','API design'],['Observability, profiling, and production debugging','Operations'],['Embedded automation and sensor-driven systems','Engineering']],external:[['Node.js and TypeScript backend systems','Stack'],['PostgreSQL-backed application architecture','Stack'],['Python, Raspberry Pi, and OpenCV','Stack'],['C++ and Electrical/Electronics engineering','Stack']]};
const perPage=6;let currentPage=1;const projectList=document.querySelector('#project-list'),pagination=document.querySelector('#pagination'),projectRange=document.querySelector('#project-range'),projectCount=document.querySelector('#project-count');
function renderProjects(page=1){currentPage=page;const start=(page-1)*perPage,visible=projects.slice(start,start+perPage);projectList.innerHTML=visible.map((p,i)=>`<article class="project-row"><div><div class="project-title-line"><span class="project-index">${String(start+i+1).padStart(2,'0')}</span><h3>${p.name}</h3><span class="project-language">${p.language}</span></div><p class="project-description">${p.description}</p><div class="tags">${p.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div></div><div class="project-links"><a href="https://github.com/Asmodeus8" target="_blank" rel="noreferrer">GitHub ↗</a></div></article>`).join('');const end=Math.min(start+perPage,projects.length);projectRange.textContent=`${start+1}–${end} of ${projects.length}`;projectCount.textContent=`${projects.length} selected builds`;const count=Math.ceil(projects.length/perPage);pagination.innerHTML=`<button data-page="${currentPage-1}" ${currentPage===1?'disabled':''}>← Prev</button>`+Array.from({length:count},(_,i)=>`<button data-page="${i+1}" ${i+1===currentPage?'aria-current="page"':''}>${i+1}</button>`).join('')+`<button data-page="${currentPage+1}" ${currentPage===count?'disabled':''}>Next →</button>`}
pagination.addEventListener('click',e=>{const b=e.target.closest('button[data-page]');if(b&&!b.disabled){renderProjects(Number(b.dataset.page));document.querySelector('#projects').scrollIntoView({behavior:'smooth'})}});
const postList=document.querySelector('#post-list'),tabs=[...document.querySelectorAll('[data-tab]')];function renderPosts(type){postList.innerHTML=posts[type].map(([t,s])=>`<article class="post-row"><a href="#contact">${t}</a><span>${s}</span></article>`).join('')}tabs.forEach(b=>b.addEventListener('click',()=>{tabs.forEach(t=>t.setAttribute('aria-selected',String(t===b)));renderPosts(b.dataset.tab)}));
const cube=document.querySelector('#cube'),stage=document.querySelector('#cube-stage');let rx=-24,ry=-34,start=null,moved=false;function update(){cube.style.setProperty('--rx',`${rx}deg`);cube.style.setProperty('--ry',`${ry}deg`)}stage.addEventListener('pointerdown',e=>{start={x:e.clientX,y:e.clientY,rx,ry};moved=false;stage.setPointerCapture(e.pointerId)});stage.addEventListener('pointermove',e=>{if(!start)return;const dx=e.clientX-start.x,dy=e.clientY-start.y;moved||=Math.abs(dx)+Math.abs(dy)>4;ry=start.ry+dx*.55;rx=Math.max(-80,Math.min(80,start.rx-dy*.55));update()});stage.addEventListener('pointerup',e=>{start=null;if(!moved){rx=-18-Math.random()*34;ry+=90+Math.round(Math.random()*2)*90;update()}stage.releasePointerCapture?.(e.pointerId)});const turns={r:()=>ry+=90,u:()=>rx-=90,f:()=>{rx+=45;ry-=45}};window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(turns[k]){turns[k]();update()}});
const toggle=document.querySelector('#theme-toggle'),meta=document.querySelector('meta[name="theme-color"]');function theme(t){document.documentElement.dataset.theme=t;meta.content=t==='dark'?'#11140f':'#faf8f6'}theme(localStorage.getItem('portfolio-theme')||'light');toggle.addEventListener('click',()=>{const n=document.documentElement.dataset.theme==='dark'?'light':'dark';theme(n);localStorage.setItem('portfolio-theme',n)});renderProjects();renderPosts('notes');